name: "CI"

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore src

      - name: Build
        run: dotnet build src --no-restore

      - name: Test
        run: dotnet test src --no-build
